### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by SeeleVolle** [ZJUEAI/class-issue#2]
The kernel 'Python 3.8.0 64-bit' died. View Jupyter [log](command:jupyter.viewOutput) for further details.
为什么我的kernel突然挂掉了，应该怎么办
![image](https://user-images.githubusercontent.com/93275435/159105687-d7dfac48-051c-4860-8df3-7deb91778fa4.png)

**Comment by floatshadow** [comment]
请问是刚刚运行挂掉还是中途挂掉（
如果是中途挂掉的话先尝试重启kernel
一开始就挂掉可能是环境的问题

**Comment by floatshadow** [comment]
Jupyter官方的issue也有人提到这个问题 [Link](https://github.com/jupyter/notebook/issues/1892#issuecomment-260403964)，
可以先自行尝试提到的解决方法

**Comment by SeeleVolle** [comment]
已经解决了谢谢Get Outlook for Android
